# Breast Cancer Prediction

Breast cancer prediction is a classification problem. we are using the sklearn's inbuilt dataset for the prediction. We are using different classification algorithms like **support vector machine, Dicision tree, Random forest, K-nearest neighbors, Naive bayes classifier & Logistic regression** for the purpose of better performance. 

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn.datasets as data

## (i) Support Vector Classification

In [7]:
dataset=data.load_breast_cancer()
dataset

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [8]:
breast_cancer_df=pd.DataFrame(data=dataset.data,columns=dataset.feature_names)
breast_cancer_df["target"]=dataset.target
breast_cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

In [9]:
x=breast_cancer_df.drop("target",axis=1)
y=breast_cancer_df["target"]

In [10]:
x

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int32

In [12]:
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split 

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2020)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(455, 30) (114, 30) (455,) (114,)


In [7]:
from sklearn.svm import SVC

**Applying on unscaled data**

In [14]:
class_rbf=SVC(kernel="rbf")
class_rbf.fit(x_train,y_train)

SVC()

**R2 score**

In [17]:
class_rbf.score(x_test,y_test)

0.9122807017543859

**On scaled data**

In [24]:
sc=StandardScaler()
sc.fit(x_train)
x_train_scale=sc.transform(x_train)
x_test_scale=sc.transform(x_test)

In [39]:
class_rbf1=SVC(kernel="rbf")
class_rbf1.fit(x_train_scale,y_train)

SVC()

**R2 Score on scaled data**

In [40]:
class_rbf1.score(x_test_scale,y_test)

0.956140350877193

Support vector classifier performed better on scaled data. So we are considering scaled data.
In support vector classifier we can use different **kernels** like **rbf, poly, linear** etc.

In [41]:
class_poly=SVC(kernel="poly",degree=2)
class_poly.fit(x_train_scale,y_train)

SVC(degree=2, kernel='poly')

In [42]:
class_poly.score(x_test_scale,y_test)

0.8333333333333334

In [43]:
class_linear=SVC(kernel="linear")
class_linear.fit(x_train_scale,y_train)

SVC(kernel='linear')

In [44]:
class_linear.score(x_test_scale,y_test)

0.9649122807017544

From above all kernels **linear** is performed better, so we are considering the model in which we have used kernel linear i.e. **class_linear** model.

**Sample prediction**

Below we have a inforamtion about a certain patient, we want predict that this person has **malignant tumor or benign tumor**.

In [45]:
patient0=[17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,
          8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,
          0.16220,0.66560,0.7119,0.2654,0.4601,0.11890]

In [46]:
patient0_scale=sc.transform(np.array([patient0]))
patient0_scale

C:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 1.14157516, -2.04268291,  1.31822055,  1.02590938,  1.62044096,
         3.42348005,  2.74540674,  2.64970572,  2.34762157,  2.34157979,
         2.47642647, -0.56729422,  2.77495792,  2.4478528 , -0.23516697,
         1.35781809,  0.68489284,  0.64085494,  1.1927004 ,  0.93126314,
         1.94777877, -1.35487239,  2.37210178,  2.06352534,  1.31020065,
         2.82342306,  2.23450433,  2.38372721,  2.86683913,  2.10454451]])

In [47]:
class_linear.predict(patient0_scale)

array([0])

above our model has given the **array([0])** i.e. patient has a **malignant tumor**.

In [48]:
dataset.target_names

array(['malignant', 'benign'], dtype='<U9')

In [49]:
patient568=np.array([7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,0.3857,
                     1.4280,2.548,19.15,0.007189,0.00466,0.00000,0.00000,0.02676,0.002783,9.456,30.37,
                     59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039])

In [51]:
patient568_scale=sc.transform([patient568])
patient568_scale

C:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.81913276,  1.21846668, -1.82334124, -1.34869964, -3.13818117,
        -1.14699319, -1.12096051, -1.27022187, -0.78765335, -0.54994985,
        -0.03734854,  0.40700372, -0.12874981, -0.43589707,  0.04118122,
        -1.14543533, -1.01143624, -1.86102377,  0.79173095, -0.36110201,
        -1.41057845,  0.76942636, -1.43238193, -1.07103161, -1.87859175,
        -1.24275657, -1.34406022, -1.768841  , -0.01272326, -0.76635844]])

In [52]:
class_linear.predict(patient568_scale)

array([1])

Above Our model given the answer **array([1])**, this means that the patient has a **benign tumor**.

## (ii) Decision Tree Classification

 Using **SVC** algorithms we have predicted a certain patient has a cancerous tumor or not, we can predict same by using **Decision Tree's Decision Tree Classification** algorithm.
 
 Below we have imported **DecisionTreeClassifier (DTC) function** to apply **Decision Tree Classification** algorithm.

In [14]:
from sklearn.tree import DecisionTreeClassifier 

In [10]:
classifier_gini=DecisionTreeClassifier(criterion="gini")
classifier_gini.fit(x_train_scale,y_train)

DecisionTreeClassifier()

In [12]:
classifier_gini.score(x_test_scale,y_test)

0.9473684210526315

Above we have applied **DTC** function with **criterion="gini"** and below we have applied **criterion="entropy"**, we can see that **gini** gives **94%** accuracy and **entropy** gives **92%** accuracy, this means **gini** performed well than **entropy**. So we are considering the **classifier_gini** model for prediction.

In [13]:
classifier_entropy=DecisionTreeClassifier(criterion="entropy")
classifier_entropy.fit(x_train_scale,y_train)

DecisionTreeClassifier(criterion='entropy')

In [14]:
classifier_entropy.score(x_test_scale,y_test)

0.9210526315789473

**Sample prediction**

In [16]:
patient564=np.array([21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,
                     1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,
                     26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115])

In [17]:
classifier_gini.predict([patient564])

array([0])

## (iii) Random Forest Classification

In [19]:
from sklearn.ensemble import RandomForestClassifier 

**On scaled data**

In [13]:
RF_classification=RandomForestClassifier(n_estimators=100,criterion="gini")
RF_classification.fit(x_train_scale,y_train)

RandomForestClassifier()

In [14]:
RF_classification.score(x_test_scale,y_test)

0.9298245614035088

**On unscaled data**

In [21]:
RF_classification1=RandomForestClassifier(n_estimators=100,criterion="gini")
RF_classification1.fit(x_train,y_train)

RandomForestClassifier()

In [22]:
RF_classification1.score(x_test,y_test)

0.9649122807017544

Random forest has given better preformance on unscaled data i.e. 96%

**Sample prediction**

In [15]:
patient564=np.array([21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,
                     1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,
                     26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115])

In [16]:
RF_classification1.predict([patient564])

C:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [17]:
patient4=np.array([20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,
                   0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,
                   152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678])

In [18]:
RF_classification1.predict([patient4])

C:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

## (iv) K-Nearest Neigbhors Classification

In [23]:
from sklearn.neighbors import KNeighborsClassifier

**On unscaled data**

In [25]:
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [13]:
classifier.score(x_test,y_test)

0.9298245614035088

**On scaled data**

In [15]:
classifier1=KNeighborsClassifier(n_neighbors=5)
classifier1.fit(x_train_scale,y_train)

KNeighborsClassifier()

In [16]:
classifier1.score(x_test_scale,y_test)

0.9473684210526315

**Sample Prediction**

In [17]:
patient567=np.array([20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,
                     1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,
                     39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400])

In [18]:
classifier1.predict([patient567])

array([0])

## (v) Naive Bayes Classifier

**Naive Bayes** used for **Classification** problems. There are three types of **Naive Bayes Classifier**: **Gaussian, Multinomial, Bernoulli**.

### (i) Gaussian Naive Bayes Classifier

In [14]:
from sklearn.naive_bayes import GaussianNB 

**On unscaled**

In [15]:
classifier_gaussian= GaussianNB()
classifier_gaussian.fit(x_train,y_train)

GaussianNB()

In [27]:
classifier_gaussian.score(x_test,y_test)

0.9473684210526315

**On scaled**

In [28]:
classifier_gaussian1= GaussianNB()
classifier_gaussian1.fit(x_train_scale,y_train)

GaussianNB()

In [29]:
classifier_gaussian1.score(x_test_scale,y_test)

0.9473684210526315

## (ii) Multinomial Naive Bayes Classifier

In [29]:
from sklearn.naive_bayes import MultinomialNB 

In [18]:
classifier_multinomial=MultinomialNB()
classifier_multinomial.fit(x_train,y_train)

MultinomialNB()

In [25]:
classifier_multinomial.score(x_test,y_test)

0.868421052631579

### (iii) Bernoulli Naive Bayes Classifier

In [20]:
from sklearn.naive_bayes import BernoulliNB 

In [33]:
classifier_bernoulli=BernoulliNB()
classifier_bernoulli.fit(x_train_scale,y_train)

BernoulliNB()

In [35]:
classifier_bernoulli.score(x_test_scale,y_test)

0.9385964912280702

## (vi) Logistic Regression

**Logistic Regression** is also use for **Classification** problems.

In [32]:
from sklearn.linear_model import LogisticRegression

In [14]:
classifier_logistic=LogisticRegression()
classifier_logistic.fit(x_train_scale,y_train)

LogisticRegression()

In [15]:
classifier_logistic.score(x_test_scale,y_test)

0.9649122807017544

**Sample Prediction**

In [16]:
patient565=np.array([20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,
                     2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,
                     38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637])

In [17]:
classifier_logistic.predict([patient565])

array([0])

## Conclusion

From above all classifiers **Logistic Regression & Random forest classifier** have performed very well based on **R2 score**, So for the breast cancer prediction we are considering **Logistic Regression or Random forest classifier** algorithm.